variables:
  COMPOSER_CACHE_DIR: "/storage"
  COMPOSER_DISABLE_XDEBUG_WARN: "1"
  COMPOSER_VENDOR_DIR: "/storage/vendor/${CI_PROJECT_ID}/${CI_BUILD_REF_NAME}"

stages:
  - test

test55:
  image: melkorm/php-docker:5.5
  stage: test
  script:
    - mkdir -p /storage/vendor/${CI_PROJECT_ID}/${CI_BUILD_REF_NAME}
    - ln -s /storage/vendor/${CI_PROJECT_ID}/${CI_BUILD_REF_NAME} vendor
    - make

test56:
  image: melkorm/php-docker:5.6
  stage: test
  script:
    - mkdir -p /storage/vendor/${CI_PROJECT_ID}/${CI_BUILD_REF_NAME}
    - ln -s /storage/vendor/${CI_PROJECT_ID}/${CI_BUILD_REF_NAME} vendor
    - make

test70:
  image: melkorm/php-docker:7.0
  stage: test
  script:
    - mkdir -p /storage/vendor/${CI_PROJECT_ID}/${CI_BUILD_REF_NAME}
    - ln -s /storage/vendor/${CI_PROJECT_ID}/${CI_BUILD_REF_NAME} vendor
    - make