variables:
  COMPOSER_CACHE_DIR: "/storage"
  COMPOSER_DISABLE_XDEBUG_WARN: "1"
  COMPOSER_VENDOR_DIR: "/storage/vendor/${CI_PROJECT_ID}/${CI_JOB_NAME}"

stages:
  - test

before_script:
  - apt-get update
  - apt-get install --assume-yes zip unzip git 
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php --filename=composer --install-dir=/usr/bin
  - php -r "unlink('composer-setup.php');"

test56:
  image: php:5.6
  stage: test
  script:
    - mkdir -p /storage/vendor/${CI_PROJECT_ID}/${CI_JOB_NAME}
    - ln -s /storage/vendor/${CI_PROJECT_ID}/${CI_JOB_NAME} vendor
    - make

test70:
  image: php:7.0
  stage: test
  script:
    - mkdir -p /storage/vendor/${CI_PROJECT_ID}/${CI_JOB_NAME}
    - ln -s /storage/vendor/${CI_PROJECT_ID}/${CI_JOB_NAME} vendor
    - make

test71:
  image: php:7.1
  stage: test
  script:
    - mkdir -p /storage/vendor/${CI_PROJECT_ID}/${CI_JOB_NAME}
    - ln -s /storage/vendor/${CI_PROJECT_ID}/${CI_JOB_NAME} vendor
    - make
