#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

//$application->add(new \CJPGDK\SALearn\SALearnCommand());
$application->add(new \CJPGDK\SALearn\VersionCommand('version'));
$application->add(new \CJPGDK\SALearn\HamCommand('ham'));
$application->add(new \CJPGDK\SALearn\SpamCommand('spam'));


$application->run();
